
version: 2

models:
    - name: fact_orders
      description: "tabela de fatos"
      columns:
          - name: order_id
            description: "a chave primária original da tabela"
            tests:
                - unique
                - not_null

    - name: dim_customers
      description: "dimensão consumidores"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
